# Generated by Django 6.0.3 on 2026-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('predicted_energy_range', models.FloatField(help_text='Predicted energy consumption range (kWh)')),
                ('peak_demand', models.FloatField(help_text='Peak demand threshold (kWh)')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RelayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mode', models.CharField(choices=[('A', 'Mode A — Peak Demand (All ON)'), ('B', 'Mode B — Average Load (P1+P2 ON)'), ('C', 'Mode C — Baseline Load (P1 ON only)')], max_length=1)),
                ('relay_1', models.BooleanField(help_text='Priority 1 relay state')),
                ('relay_2', models.BooleanField(help_text='Priority 2 relay state')),
                ('relay_3', models.BooleanField(help_text='Priority 3 relay state')),
                ('reason', models.TextField(help_text='Human-readable reason for this decision')),
            ],
            options={
                'verbose_name': 'Relay State',
                'verbose_name_plural': 'Relay States',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature', models.FloatField(help_text='Average temperature (°C)')),
                ('humidity', models.FloatField(help_text='Average humidity (%)')),
                ('occupancy', models.IntegerField(help_text='Dominant occupancy state: 1 = occupied, 0 = empty')),
                ('voltage', models.FloatField(help_text='Average voltage (V)')),
                ('current', models.FloatField(help_text='Average current (A)')),
                ('battery_level', models.FloatField(help_text='Average battery level (%)')),
            ],
            options={
                'verbose_name': 'Sensor Log',
                'verbose_name_plural': 'Sensor Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
