# Generated by Django 6.0.3 on 2026-06-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlprediction',
            name='peak_demand',
        ),
        migrations.RemoveField(
            model_name='mlprediction',
            name='predicted_energy_range',
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='lower_bound_wh',
            field=models.FloatField(default=0.0, help_text='Lower bound of prediction (Wh)'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='predicted_energy_wh',
            field=models.FloatField(default=0.0, help_text='Predicted energy consumption (Wh)'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='upper_bound_wh',
            field=models.FloatField(default=0.0, help_text='Upper bound of prediction (Wh)'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='battery_level',
            field=models.FloatField(default=0.0, help_text='Battery SoC (%) at decision time'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='battery_voltage',
            field=models.FloatField(default=0.0, help_text='Battery voltage (V) at decision time'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='energy_kw',
            field=models.FloatField(default=0.0, help_text='Energy (kWh) at decision time'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='humidity',
            field=models.FloatField(default=0.0, help_text='Humidity (%) at decision time'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='lux',
            field=models.FloatField(default=0.0, help_text='Ambient light (lx) at decision time'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='occupancy',
            field=models.IntegerField(default=0, help_text='Occupancy state at decision time'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='temperature',
            field=models.FloatField(default=0.0, help_text='Temperature (°C) at decision time'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='battery_voltage',
            field=models.FloatField(default=0.0, help_text='Average battery voltage (V)'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='energy_kw',
            field=models.FloatField(default=0.0, help_text='Average energy (kWh)'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='lux',
            field=models.FloatField(default=0.0, help_text='Average ambient light (lx)'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='power_w',
            field=models.FloatField(default=0.0, help_text='Average power (W)'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='radar_motion',
            field=models.IntegerField(default=0, help_text='Dominant radar motion state'),
        ),
        migrations.AlterField(
            model_name='relaystate',
            name='mode',
            field=models.CharField(choices=[('A', 'Smart A — Peak Load (All ON)'), ('B', 'Smart B — Moderate Load (R1+R2 ON)'), ('C', 'Smart C — Baseline Load (R1 ON only)'), ('MANUAL', 'Manual Override')], max_length=6),
        ),
    ]
