# Generated by Django 6.0.3 on 2026-06-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_remove_mlprediction_peak_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystate',
            name='upper_bound_1',
            field=models.FloatField(default=0.0, help_text='Most recent (current) upper bound value (Wh)'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='upper_bound_2',
            field=models.FloatField(default=0.0, help_text='Second most recent upper bound value (Wh)'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='upper_bound_3',
            field=models.FloatField(default=0.0, help_text='Third most recent upper bound value (Wh)'),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='upper_bound_avg',
            field=models.FloatField(default=0.0, help_text='Calculated average of the three upper bound values (Wh)'),
        ),
    ]
