# Generated by Django 6.0.3 on 2026-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprediction',
            name='safety_lower_bound',
            field=models.FloatField(default=0.0, help_text='95% confidence lower bound (kWh)'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='safety_upper_bound',
            field=models.FloatField(default=0.0, help_text='95% confidence upper bound (kWh)'),
        ),
    ]
